"""empty message

Revision ID: 1ab5a0017071
Revises: 7ea507683753
Create Date: 2020-04-15 14:40:47.307756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab5a0017071'
down_revision = '7ea507683753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_attendance', sa.Column('snid', sa.String(length=200), nullable=False))
    op.add_column('employee_attendance', sa.Column('snname', sa.String(length=200), nullable=False))
    op.add_column('employee_attendance', sa.Column('unname', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_attendance', 'unname')
    op.drop_column('employee_attendance', 'snname')
    op.drop_column('employee_attendance', 'snid')
    # ### end Alembic commands ###
