"""empty message

Revision ID: 1d4f500c358e
Revises: 
Create Date: 2020-04-01 17:41:37.978565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d4f500c358e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title_confirmdate', sa.DateTime(), nullable=True),
    sa.Column('base_brdname', sa.String(length=100), nullable=False),
    sa.Column('base_shopno', sa.String(length=100), nullable=False),
    sa.Column('base_company', sa.String(length=100), nullable=False),
    sa.Column('base_expiredate', sa.String(length=200), nullable=True),
    sa.Column('mem_check', sa.Integer(), nullable=False),
    sa.Column('mem_silverdiscount', sa.String(length=100), nullable=True),
    sa.Column('mem_gloddiscount', sa.String(length=100), nullable=True),
    sa.Column('mem_diamonddiscount', sa.String(length=100), nullable=True),
    sa.Column('mem_other', sa.Text(), nullable=True),
    sa.Column('sign_signature', sa.String(length=100), nullable=True),
    sa.Column('sign_contact', sa.String(length=100), nullable=True),
    sa.Column('sign_call', sa.String(length=100), nullable=True),
    sa.Column('sign_email', sa.String(length=100), nullable=True),
    sa.Column('sign_replydate', sa.DateTime(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title_confirmdate', sa.DateTime(), nullable=True),
    sa.Column('title_vipperson', sa.String(length=100), nullable=True),
    sa.Column('title_vipemail', sa.String(length=100), nullable=True),
    sa.Column('title_viptel', sa.String(length=100), nullable=True),
    sa.Column('base_brdname', sa.String(length=100), nullable=False),
    sa.Column('base_shopno', sa.String(length=100), nullable=False),
    sa.Column('base_company', sa.String(length=100), nullable=False),
    sa.Column('spcard_check', sa.Integer(), nullable=False),
    sa.Column('spcard_shopmall', sa.String(length=200), nullable=True),
    sa.Column('remark_policy', sa.Text(), nullable=True),
    sa.Column('remark_contact', sa.String(length=100), nullable=True),
    sa.Column('sign_signature', sa.String(length=100), nullable=True),
    sa.Column('sign_contact', sa.String(length=100), nullable=True),
    sa.Column('sign_call', sa.String(length=100), nullable=True),
    sa.Column('sign_email', sa.String(length=100), nullable=True),
    sa.Column('sign_replydate', sa.DateTime(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=False),
    sa.Column('updated_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_feedback')
    op.drop_table('gift_feedback')
    # ### end Alembic commands ###
