"""empty message

Revision ID: 4c3c0b3122ed
Revises: ffb023f57b7c
Create Date: 2020-04-15 16:15:35.672460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c3c0b3122ed'
down_revision = 'ffb023f57b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_attendance_device', sa.Column('ip', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_attendance_device', 'ip')
    # ### end Alembic commands ###
