"""empty message

Revision ID: 7ea507683753
Revises: 1d4f500c358e
Create Date: 2020-04-08 16:00:06.921113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea507683753'
down_revision = '1d4f500c358e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('checktime', sa.DateTime(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_attendance')
    # ### end Alembic commands ###
