"""empty message

Revision ID: 7faa04ab09b6
Revises: a18e49fcba3d
Create Date: 2020-05-09 10:17:30.622937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7faa04ab09b6'
down_revision = 'a18e49fcba3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_participant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('signdate', sa.DateTime(), nullable=False),
    sa.Column('label', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_participant')
    # ### end Alembic commands ###
