"""empty message

Revision ID: a18e49fcba3d
Revises: 4c3c0b3122ed
Create Date: 2020-04-21 14:32:59.210346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18e49fcba3d'
down_revision = '4c3c0b3122ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_attendance', sa.Column('status', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_attendance', 'status')
    # ### end Alembic commands ###
