"""empty message

Revision ID: d014fc3217c4
Revises: 7faa04ab09b6
Create Date: 2020-05-11 17:04:12.078043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd014fc3217c4'
down_revision = '7faa04ab09b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_attendance', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_attendance', 'image')
    # ### end Alembic commands ###
