"""empty message

Revision ID: ffb023f57b7c
Revises: 1ab5a0017071
Create Date: 2020-04-15 15:10:57.043149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb023f57b7c'
down_revision = '1ab5a0017071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_attendance_device',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snid', sa.String(length=200), nullable=False),
    sa.Column('snname', sa.String(length=200), nullable=False),
    sa.Column('unname', sa.String(length=200), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_attendance_device')
    # ### end Alembic commands ###
